name: CI

on:
  push:
    branches: [main] # trigger the workflow only when there are new commits to the main branch

jobs:
  build:

    runs-on: ubuntu-latest # run the job on a Linux-based environment

    steps:
    - name: Checkout code # check out the code from the repository
      uses: actions/checkout@v2

    - name: Setup Node.js # set up Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14.x' # specify Node.js version

    - name: Install dependencies # install project dependencies
      run: npm install

    - name: Check for updates # check if there are any updates to the code base
      run: |
        git fetch --prune
        if [ `git rev-parse HEAD` = `git rev-parse @{u}` ]; then # if there are no updates, skip the build
          echo "No updates available, skipping build"
          exit 0
        fi

    - name: Build and test # build and test the project
      run: |
        npm install # install any new dependencies
        npm run build # build the project
        npm test # run tests

    - name: Push changes # push changes to the repository
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} # authenticate with the GITHUB_TOKEN secret
        branch: ${{ github.ref }} # push changes to the same branch that triggered the workflow
        force: true # force push changes

    - name: Log result # log the result of the push
      if: ${{ success() }} # if the push was successful, log "Push was successful"
      run: echo "Push was successful"
      else # otherwise, log "Push failed, please check logs"
      run: echo "Push failed, please check logs"

    - name: Send error log message # log an error message if the build failed
      if: failure() # if the build failed, log "Build failed! Check the logs for details."
      run: |
        echo "Build failed! Check the logs for details."
